// Code generated by `mygo generate`. DO NOT EDIT.

import { call } from "mygo-runtime";

// ---- Types ----

export interface Appearance {
  theme: string;
  radius: number;
  colors: Record<string, string>;
}

/** Config is the portable identity/data configuration, not domain authority. */
export interface Config {
  theme: string;
  radius: number;
  omarchy_file: string;
}

export interface Envelope {
  version: string;
  ok: boolean;
  result?: Result;
  error?: Failure;
}

export interface Failure {
  code: string;
  message: string;
}

export interface Item {
  id: string;
  label: string;
}

/** Request is shared by typed desktop IPC and semantic CLI commands. */
export interface Request {
  operation: string;
  input: string;
}

export interface Result {
  snapshot?: Snapshot;
  appearance?: Appearance;
  config?: Config;
}

export interface Snapshot {
  revision: string;
  items: Item[];
}

// ---- Services ----

/** Desktop exposes only semantic operations, not host lifecycle/configuration. */
export const Desktop = {
  /** Execute uses the exact service called by the headless CLI. */
  execute(request: Request): Promise<Envelope> {
    return call("Desktop.Execute", request);
  },
} as const;
